### PR TITLE
NXP-27912: move web ui ftests to its repo

### PR DESCRIPTION
**Pull request by nmpcunha**
Related to: https://github.com/nuxeo/nuxeo-web-ui/pull/709

### CODE REVIEW

**Review by Gabez0r — APPROVED** [review]

**Review by Gabez0r — CHANGES_REQUESTED** [review]
need to update the pom.xml file:
```
<profiles>
    <profile>
      <id>ftest</id>
      <modules>
        <module>ftest/jsf-ui/webdriver</module>
        <module>ftest/web-ui/webdriver</module>
      </modules>
    </profile>
    <profile>
      <id>jsf-ui-ftest</id>
      <modules>
        <module>ftest/jsf-ui/webdriver</module>
      </modules>
    </profile>
    <profile>
      <id>web-ui-ftest</id>
      <modules>
        <module>ftest/web-ui/webdriver</module>
      </modules>
    </profile>
  </profiles>
```

**Review by Gabez0r — APPROVED** [review]

**Comment by guirenard** [comment]
I understand DAM Web UI functional tests won't be executed anymore after that?
(https://github.com/nuxeo/nuxeo-web-ui/pull/709#issuecomment-530471059)

**Comment by nmpcunha** [comment]
You are correct, the tests won't run. But, we can hold the merge until a decision is made on how those tests will run on WebUI.
Anyway, for master we don't expect changes to be done here, which means that the tests won't run anyway...

**Review by guirenard — CHANGES_REQUESTED** [review]
I don't think https://github.com/nuxeo/marketplace-dam/blob/master/pom.xml#L47 is needed anymore  (the ultimate goal is to remove the dep on the Web UI marketplace) in which case you would now need to:
 - remove the left-over `marketplace.webui.version` property https://github.com/nuxeo/nuxeo-web-ui/blob/2e9eabe9c0236f7b4870e319b7e824d9dd5aabb8/pom.xml#L21
 - remove in marketplace.ini version sed https://github.com/nuxeo/integration-scripts/blob/master/marketplace.ini#L91

**Review by guirenard — APPROVED** [review]

**Review by Gabez0r — APPROVED** [review]

**Pull request merged**
